name: superuser
description: A product by shanmukeshwar and gautham

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  firebase_auth:
  firebase_core:
  cloud_firestore:
  material_design_icons_flutter:
  firebase_storage:
  date_time_format:
  cached_network_image:
  photo_view:
  flutter_spinkit:
  lazy_load_scrollview:
  flutter_data_stream_builder:
  get:
  url_launcher:
  cloud_functions:
  image_picker:
  image_cropper:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
